version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "neo4j/test"
    ports:
      - "7474:7474"   # HTTP / Browser
      - "7687:7687"   # BOLT
    volumes:
      - data:/data

volumes:
  data: {}
